
[project]
name = "evalassist"
dynamic = ["version"]
description = "EvalAssist is an open-source project that simplifies using large language models as evaluators (LLM-as-a-Judge) of the output of other large language models by supporting users in iteratively refining evaluation criteria in a web-based user experience."
license = "Apache-2.0" # set your license here
requires-python = ">=3.10,<3.14"
authors = [
    { name = "Martín Santillán Cooper", email = "martinsantillancooper@gmail.com" },
]
keywords = ["LLM", "evaluation", "LLM-as-a-Judge", "AI-evaluation"]
classifiers = [
    # Project maturity
    "Development Status :: 4 - Beta",

    # Intended audience
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: End Users/Desktop",

    # License
    "License :: OSI Approved :: Apache Software License",

    # Supported Python versions
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",

    # Supported operating systems
    "Operating System :: OS Independent",

    # Project topics
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Text Processing :: Linguistic",

    # Frameworks and tools
    "Framework :: FastAPI",
    "Framework :: Jupyter",
]

dependencies = ["pydantic==2.11.7", "unitxt==1.26.6"]

[tool.poetry]
packages = [{ include = "evalassist", from = "src" }]
include = [
    { path = "evalassist/static/**/*", format = "sdist" },
    { path = "evalassist/static/**/*", format = "wheel" },
    { path = "evalassist/alembic.ini", format = "sdist" },
    { path = "evalassist/alembic.ini", format = "wheel" },
]
version = "0.0.0"

[project.optional-dependencies]
dev = [
    "pre_commit==4.2.0",
    "bandit[standard,toml]==1.8.5",
    "flake8-pytest-style==2.1.0",
    "flake8==7.3.0",
    "GitPython==3.1.44",
    "pytest==8.4.1",
    "httpx==0.28.1",
    "tox==4.27.0",
    "pytest-cov==6.2.1",
]
webapp = [
    "litellm==1.73.0",
    "openai==1.90.0",
    "ollama==0.5.1",
    "ibm_watsonx_ai==1.3.26",
    "fastapi==0.115.13",
    "uvicorn==0.34.3",
    "nest_asyncio==1.6.0",
    "nbformat==5.10.4",
    "tenacity==9.1.2",
    "diskcache==5.6.3",
    "pandas==2.2.3",
    "nbconvert==7.16.6",
    "boto3==1.38.41",
    "click==8.2.1",
    "setuptools==80.9.0",
    "sqlmodel==0.0.24",
    "alembic==1.16.2",
]
benchmarks = ["scikit-learn==1.7.0"]
postgresql = ["psycopg2-binary==2.9.10"]
local-inference = ["torch==2.7.1", "accelerate==1.8.1", "transformers==4.53.2"]
prometheus = ["vllm==0.10.0", "prometheus-eval==0.1.20"]

[tool.pytest.ini_options]
addopts = "--cov=evalassist"

[project.scripts]
eval-assist = "evalassist.cli:main"

[project.urls]
homepage = "https://ibm.github.io/eval-assist/"
repository = "https://github.com/IBM/eval-assist"
documentation = "https://github.com/IBM/eval-assist/wiki"
"Bug Tracker" = "https://github.com/IBM/eval-assist/issues"


[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }
poetry-plugin-export = ">=1.8"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
metadata = false

[tool.bandit]
exclude_dirs = [".venv", "venv", ".poetry", "dist", "tests"]
