services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: eval-assist-db
      POSTGRES_PASSWORD: admin # pragma: allowlist secret
    ports:
      - 5432:5432
    networks:
      default:

volumes:
  postgres-data:
