name: Verify Backend Code Quality & Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install requirements
        working-directory: backend
        run: |
          pip install poetry
          poetry install --with dev
      - name: Install the pre-commit hooks
        working-directory: backend
        run: |
          pre-commit install
      - name: Validate all pre-commit verification were run correctly
        working-directory: backend
        run: |
          pre-commit run --all-files
      - name: Send failure message
        if: failure() # This step will only run if a previous step failed
        run: echo "The quality & security verification failed. This is likely due to not using pre-commit hooks please run 'pre-commit install' before any commit."
